CREATE TABLE `spa_loan_purchase_price` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `Document_ID` int NOT NULL,
  `Document_Type_Name` varchar(255) NOT NULL DEFAULT '',
  `Document_Agreement_Name` varchar(255) NOT NULL DEFAULT '',
  `Purchase_Price` decimal(19,4) NOT NULL ,
  `Earnest_Deposit` decimal(19,4) NOT NULL ,
  `RPGT_Retention_Sum` decimal(19,4) NOT NULL ,
  `Balance_Deposit` decimal(19,4) NOT NULL,
  `Total Deposit` decimal(19,4) NOT NULL,
  `Balance_Purchase_Price` decimal(19,4) NOT NULL,
  `Consuption_Tax` decimal(19,4) NOT NULL,
  `Purchase_Price_After_Tax` decimal(19,4) NOT NULL , 
  `Adjustment_Rate`  decimal(19,4) NOT NULL  ,
  `Bank_Branch_ID` int default null , 
  `Charge_Presentation_No` varchar(255) DEFAULT '' , 
  `Existing_Borrower1_User_ID` int DEFAULT NULL,
  `Existing_Borrower2_User_ID` int DEFAULT NULL,
  `Existing_Borrower3_User_ID` int DEFAULT NULL,
  `Existing_Borrower4_User_ID` int DEFAULT NULL,
  `Existing_Borrower5_User_ID` int DEFAULT NULL,
  `CreatedDate` timestamp NULL DEFAULT NULL,
  `CreatedBy` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL, 
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `spa_loan_individual` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `Document_ID` int NOT NULL,
  `Document_Type_Name` varchar(255) NOT NULL DEFAULT '',
  `Document_Agreement_Name` varchar(255) NOT NULL DEFAULT '',
  `Owning_Type_Id` int default NULL ,
  `Lot_Type_Id` int default NULL ,
  `Daerah_Id` int default NULL ,
  `State_Id` int default NULL ,
  `Area_Id` int default NULL ,
  `Geran_Status_Type_ID` int default NULL ,
  `Lease_Expiry_Date` datetime DEFAULT NULL,
  `Condition_Type_ID` int default NULL,
  `Restriction_Type_ID` int default NULL,
  `Building_Type_ID` int default null,
  `Postal_Address` varchar(255) default '',
  `CreatedDate` timestamp NULL DEFAULT NULL,
  `CreatedBy` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL, 
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `spa_loan_strata` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `DocumentId` int NOT NULL,
  `Document_Type_Name` varchar(255) NOT NULL DEFAULT '',
  `Document_Agreement_Name` varchar(255) NOT NULL DEFAULT '',
  `Owning_Type_Id` int default NULL ,
  `Lot_Type_Id` int default NULL ,
  `Daerah_Id` int default NULL ,
  `State_Id` int default NULL ,
  `Area_Id` int default NULL ,
  `Geran_Status_Type_Id` int default NULL ,
  `Lease_Expiry_Date` datetime DEFAULT NULL,
  `Condition_Type_Id` int default NULL,
  `Restriction_Type_Id` int default NULL,
  `Building_Type_Id` int default null,
  `Postal_Address` varchar(255) default '',
  `Parcel_No` varchar(255) default '' ,
  `Story_No` varchar(255) default '' ,
  `Building_No` varchar(255) default '' ,
  `Accessory_Parcel_No` varchar(255) default '',
  `Unit_Area`int default NULL ,
  `CreatedDate` timestamp NULL DEFAULT NULL,
  `CreatedBy` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL, 
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `spa_loan_without_transfer_direct_transfer` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `DocumentId` int NOT NULL,
  `Document_Type_Name` varchar(255) NOT NULL DEFAULT '',
  `Document_Agreement_Name` varchar(255) NOT NULL DEFAULT '',
  `Owning_Type_Id` int default NULL ,
  `Lot_Type_Id` int default NULL ,
  `Daerah_Id` int default NULL ,
  `State_Id` int default NULL ,
  `Area_Id` int default NULL ,
  `Geran_Status_Type_Id` int default NULL ,
  `Lease_Expiry_Date` datetime DEFAULT NULL,
  `Condition_Type_Id` int default NULL,
  `Restriction_Type_Id` int default NULL,
  `Building_Type_Id` int default null,
  `Postal_Address` varchar(255) default '',
  `Parcel_No` varchar(255) default '' ,
  `Story_No` varchar(255) default '' ,
  `Building_No` varchar(255) default '' ,
  `Accessory_Parcel_No` varchar(255) default '',
  `Unit_Area`int default NULL ,
  `CreatedDate` timestamp NULL DEFAULT NULL,
  `CreatedBy` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL, 
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `spa_loan_chain_of_ownership` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `DocumentId` int NOT NULL,
  `Document_Type_Name` varchar(255) NOT NULL DEFAULT '',
  `Document_Agreement_Name` varchar(255) NOT NULL DEFAULT '',
  `Purchaser1_User_ID` int DEFAULT NULL,
  `Purchaser2_User_ID` int DEFAULT NULL,
  `Purchaser3_User_ID` int DEFAULT NULL,
  `Purchaser4_User_ID` int DEFAULT NULL,
  `Purchaser5_User_ID` int DEFAULT NULL,
  `Purchaser6_User_ID` int DEFAULT NULL,
  `Purchaser7_User_ID` int DEFAULT NULL,
  `CreatedDate` timestamp NULL DEFAULT NULL,
  `CreatedBy` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL, 
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `spa_loan_for_loan` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `DocumentId` int NOT NULL,
  `Document_Type_Name` varchar(255) NOT NULL DEFAULT '',
  `Document_Agreement_Name` varchar(255) NOT NULL DEFAULT '',
  `Borrower1_User_ID` int DEFAULT NULL ,
  `Borrower2_User_ID` int DEFAULT NULL ,
  `Borrower3_User_ID` int DEFAULT NULL ,
  `Borrower4_User_ID` int DEFAULT NULL ,
  `Borrower5_User_ID` int DEFAULT NULL ,
  `Guarantor1_User_ID` int DEFAULT NULL,
  `Guarantor2_User_ID` int DEFAULT NULL,
  `Guarantor3_User_ID` int DEFAULT NULL,
  `Guarantor4_User_ID` int DEFAULT NULL,
  `Guarantor5_User_ID` int DEFAULT NULL,
  `Bank_Branch_ID` int DEFAULT NULL,
  `Bank_Reference` varchar(255) NOT NULL DEFAULT '',
  `Offer_Letter_Date` DATETIME DEFAULT NULL,
  `Letter_of_Instruction_Date` DATETIME DEFAULT NULL,
  `Officer1_Name` varchar(255) NOT NULL DEFAULT '' ,
  `Officer1_Username`  varchar(255) NOT NULL DEFAULT '' ,
  `Officer1_Password`  varchar(255) NOT NULL DEFAULT '' ,
  `Officer2_Name`  varchar(255) NOT NULL DEFAULT '' ,
  `Officer2_Username`  varchar(255) NOT NULL DEFAULT '' ,
  `Officer2_Password` varchar(255) NOT NULL DEFAULT '' ,
  `Conventional_Loan_Type` int DEFAULT NULL ,
  `Conventional_Financing_Type` int DEFAULT NULL,
  `Conventional_Loan_Amount` decimal(19,4) NOT NULL ,
  `Other_Loan1_Type` int DEFAULT NULL,
  `Other_Loan1_Amount` decimal(19,4) NOT NULL ,
  `Other_Loan2_Type`  int DEFAULT NULL,
  `Other_Loan2_Amount` decimal(19,4) NOT NULL ,
  `Other_Loan3_Type` int DEFAULT NULL,
  `Other_Loan3_Amount` decimal(19,4) NOT NULL ,
  `Other_Loan4_Type` int DEFAULT NULL,
  `Other_Loan4_Amount` decimal(19,4) NOT NULL ,
  `Other_Loan5_Type` int DEFAULT NULL,
  `Other_Loan5_Amount`decimal(19,4) NOT NULL  ,
  `Other_Loan6_Type` int DEFAULT NULL,
  `Other_Loan6_Amount` decimal(19,4) NOT NULL ,
  `Conventional_Loan_Total_Financing_Sum` decimal(19,4) NOT NULL  ,
  `Islamic_Loan_Type` int DEFAULT NULL,
  `Islamic_Financing_Type` int DEFAULT NULL,
  `Islamic_Financing_Amount` decimal(19,4) NOT NULL  ,
  `Other_Financing1_Type` int DEFAULT NULL,
  `Other_Financing1_Amount` decimal(19,4) NOT NULL  ,
  `Other_Financing2_Type` int DEFAULT NULL,
  `Other_Financing2_Amount` decimal(19,4) NOT NULL  ,
  `Other_Financing3_Type` int DEFAULT NULL,
  `Other_Financing3_Amount` decimal(19,4) NOT NULL ,
  `Other_Financing4_Type` int DEFAULT NULL,
  `Other_Financing4_Amount` decimal(19,4) NOT NULL ,
  `Other_Financing5_Type` int DEFAULT NULL,
  `Other_Financing5_Amount` decimal(19,4) NOT NULL ,
  `Islamic_Loan_Total_Financing_Sum` decimal(19,4) NOT NULL ,
  `Bank_Selling_Price` decimal(19,4) NOT NULL ,
  `Bank_Purchase_Price` decimal(19,4) NOT NULL ,
  `Other_Islamic_Loan1_Bank_Name` varchar(255) NOT NULL DEFAULT '',
  `Other_Islamic_Loan1_Product_Type` varchar(255) NOT NULL DEFAULT '' ,
  `Other_Islamic_Loan1_Specification` varchar(255) NOT NULL DEFAULT '',
  `Other_Islamic_Loan1_Amount` decimal(19,4) NOT NULL ,
  `Other_Islamic_Loan1_Unit_Percentage` decimal(19,4) NOT NULL ,
  `Other_Islamic_Loan1_Ref` varchar(255) NOT NULL DEFAULT '',
  `Other_Islamic_Loan2_Bank_Name` varchar(255) NOT NULL DEFAULT '' ,
  `Other_Islamic_Loan2_Product_Type` varchar(255) NOT NULL DEFAULT '',
  `Other_Islamic_Loan2_Specification` varchar(255) NOT NULL DEFAULT '',
  `Other_Islamic_Loan2_Amount` decimal(19,4) NOT NULL ,
  `Other_Islamic_Loan2_Unit_Percentage`decimal(19,4) NOT NULL  ,
  `Other_Islamic_Loan2_Ref` varchar(255) NOT NULL DEFAULT '',
  `Other_Islamic_Loan3_Bank_Name` varchar(255) NOT NULL DEFAULT '',
  `Other_Islamic_Loan3_Product_Type` varchar(255) NOT NULL DEFAULT '',
  `Other_Islamic_Loan3_Specification` varchar(255) NOT NULL DEFAULT '',
  `Other_Islamic_Loan3_Amount`decimal(19,4) NOT NULL  ,
  `Other_Islamic_Loan3_Unit_Percentage`decimal(19,4) NOT NULL  ,
  `Other_Islamic_Loan3_Ref` varchar(255) NOT NULL DEFAULT '',
  `Bank_Solicitor_ID`  int DEFAULT NULL,
  `Bank_Solicitor_Firm_Phone_No` varchar(255) NOT NULL DEFAULT '',
  `Bank_Solicitor_Firm_Location` varchar(255) NOT NULL DEFAULT '',
  `Bank_Solicitor_Ref` varchar(255) NOT NULL DEFAULT '',
  `Bank_Solicitor_Email` varchar(255) NOT NULL DEFAULT '',
  `CreatedDate` timestamp NULL DEFAULT NULL,
  `CreatedBy` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL, 
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

