//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSLcLy.Data.DbModels
{
    using System;
    using System.Collections.Generic;

    [System.ComponentModel.DataAnnotations.Schema.Table("enummaster")]
    public partial class enummaster
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int Id { get; set; }
        public string EnumType { get; set; }
        public string EnumName { get; set; }
        public string EnumValue { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public sbyte IsFavourite { get; set; }
    }
}
