//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSLcLy.Data.DbModels
{
    using System;
    using System.Collections.Generic;
    [System.ComponentModel.DataAnnotations.Schema.Table("spa_loan_chain_of_ownership")]
    public partial class spa_loan_chain_of_ownership
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int ID { get; set; }
        public int DocumentId { get; set; }
        public string Document_Type_Name { get; set; }
        public string Document_Agreement_Name { get; set; }
        public Nullable<int> Purchaser1_User_ID { get; set; }
        public Nullable<int> Purchaser2_User_ID { get; set; }
        public Nullable<int> Purchaser3_User_ID { get; set; }
        public Nullable<int> Purchaser4_User_ID { get; set; }
        public Nullable<int> Purchaser5_User_ID { get; set; }
        public Nullable<int> Purchaser6_User_ID { get; set; }
        public Nullable<int> Purchaser7_User_ID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Purchaser1_DOA_Date { get; set; }
        public Nullable<System.DateTime> Purchaser1_FA_Date { get; set; }
        public Nullable<System.DateTime> Purchaser1_Loan_Date { get; set; }
        public Nullable<System.DateTime> Purchaser1_DRR_Date { get; set; }
        public Nullable<System.DateTime> Purchaser2_DOA_Date { get; set; }
        public Nullable<System.DateTime> Purchaser2_FA_Date { get; set; }
        public Nullable<System.DateTime> Purchaser2_Loan_Date { get; set; }
        public Nullable<System.DateTime> Purchaser2_DRR_Date { get; set; }
        public Nullable<System.DateTime> Purchaser3_DOA_Date { get; set; }
        public Nullable<System.DateTime> Purchaser3_FA_Date { get; set; }
        public Nullable<System.DateTime> Purchaser3_Loan_Date { get; set; }
        public Nullable<System.DateTime> Purchaser3_DRR_Date { get; set; }
        public Nullable<System.DateTime> Purchaser4_DOA_Date { get; set; }
        public Nullable<System.DateTime> Purchaser4_FA_Date { get; set; }
        public Nullable<System.DateTime> Purchaser4_Loan_Date { get; set; }
        public Nullable<System.DateTime> Purchaser4_DRR_Date { get; set; }
        public Nullable<System.DateTime> Purchaser5_DOA_Date { get; set; }
        public Nullable<System.DateTime> Purchaser5_FA_Date { get; set; }
        public Nullable<System.DateTime> Purchaser5_Loan_Date { get; set; }
        public Nullable<System.DateTime> Purchaser5_DRR_Date { get; set; }
        public Nullable<System.DateTime> Purchaser6_DOA_Date { get; set; }
        public Nullable<System.DateTime> Purchaser6_FA_Date { get; set; }
        public Nullable<System.DateTime> Purchaser6_Loan_Date { get; set; }
        public Nullable<System.DateTime> Purchaser6_DRR_Date { get; set; }
        public Nullable<System.DateTime> Purchaser7_DOA_Date { get; set; }
        public Nullable<System.DateTime> Purchaser7_FA_Date { get; set; }
        public Nullable<System.DateTime> Purchaser7_Loan_Date { get; set; }
        public Nullable<System.DateTime> Purchaser7_DRR_Date { get; set; }
    }
}
