//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSLcLy.Data.DbModels
{
    using System;
    using System.Collections.Generic;
    [System.ComponentModel.DataAnnotations.Schema.Table("spa_loan_strata")]
    public partial class spa_loan_strata
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int ID { get; set; }
        public int DocumentId { get; set; }
        public string Document_Type_Name { get; set; }
        public string Document_Agreement_Name { get; set; }
        public Nullable<int> State_Id { get; set; }
        public Nullable<int> Area_Id { get; set; }
        public Nullable<int> Condition_Type_Id { get; set; }
        public Nullable<int> Restriction_Type_Id { get; set; }
        public Nullable<int> Building_Type_Id { get; set; }
        public string Postal_Address { get; set; }
        public string Parcel_No { get; set; }
        public string Story_No { get; set; }
        public string Building_No { get; set; }
        public Nullable<int> Unit_Area { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> Tenure_Type_Id { get; set; }
        public Nullable<int> Land_Usage_Type_Id { get; set; }
        public Nullable<int> Area_Type_Id { get; set; }
        public Nullable<int> Geran_Type_Id { get; set; }
        public Nullable<System.DateTime> Date_Open_File { get; set; }
        public string Parcel_No_Description { get; set; }
        public Nullable<int> Lot_Type_Id { get; set; }
    }
}
