//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSLcLy.Data.DbModels
{
    using System;
    using System.Collections.Generic;

    [System.ComponentModel.DataAnnotations.Schema.Table("spa_loan_purchase_price")]
    public partial class spa_loan_purchase_price
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int ID { get; set; }
        public int Document_ID { get; set; }
        public string Document_Type_Name { get; set; }
        public string Document_Agreement_Name { get; set; }
        public decimal Purchase_Price { get; set; }
        public decimal Earnest_Deposit { get; set; }
        public decimal RPGT_Retention_Sum { get; set; }
        public decimal Balance_Deposit { get; set; }
        public decimal Total_Deposit { get; set; }
        public decimal Balance_Purchase_Price { get; set; }
        public decimal Consuption_Tax { get; set; }
        public decimal Purchase_Price_After_Tax { get; set; }
        public decimal Adjustment_Rate { get; set; }
        public Nullable<int> Bank_Branch_ID { get; set; }
        public string Charge_Presentation_No { get; set; }
        public Nullable<int> Existing_Borrower1_User_ID { get; set; }
        public Nullable<int> Existing_Borrower2_User_ID { get; set; }
        public Nullable<int> Existing_Borrower3_User_ID { get; set; }
        public Nullable<int> Existing_Borrower4_User_ID { get; set; }
        public Nullable<int> Existing_Borrower5_User_ID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
