//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSLcLy.Data.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class spa_loan_for_loan
    {
        public int ID { get; set; }
        public int DocumentId { get; set; }
        public string Document_Type_Name { get; set; }
        public string Document_Agreement_Name { get; set; }
        public Nullable<int> Borrower1_User_ID { get; set; }
        public Nullable<int> Borrower2_User_ID { get; set; }
        public Nullable<int> Borrower3_User_ID { get; set; }
        public Nullable<int> Borrower4_User_ID { get; set; }
        public Nullable<int> Borrower5_User_ID { get; set; }
        public Nullable<int> Guarantor1_User_ID { get; set; }
        public Nullable<int> Guarantor2_User_ID { get; set; }
        public Nullable<int> Guarantor3_User_ID { get; set; }
        public Nullable<int> Guarantor4_User_ID { get; set; }
        public Nullable<int> Guarantor5_User_ID { get; set; }
        public Nullable<int> Bank_Branch_ID { get; set; }
        public string Bank_Reference { get; set; }
        public Nullable<System.DateTime> Offer_Letter_Date { get; set; }
        public Nullable<System.DateTime> Letter_of_Instruction_Date { get; set; }
        public string Officer1_Username { get; set; }
        public string Officer1_Password { get; set; }
        public string Officer2_Username { get; set; }
        public string Officer2_Password { get; set; }
        public Nullable<int> Conventional_Loan_Type { get; set; }
        public Nullable<int> Conventional_Financing_Type { get; set; }
        public decimal Conventional_Loan_Amount { get; set; }
        public Nullable<int> Other_Loan1_Type { get; set; }
        public decimal Other_Loan1_Amount { get; set; }
        public Nullable<int> Other_Loan2_Type { get; set; }
        public decimal Other_Loan2_Amount { get; set; }
        public Nullable<int> Other_Loan3_Type { get; set; }
        public decimal Other_Loan3_Amount { get; set; }
        public Nullable<int> Other_Loan4_Type { get; set; }
        public decimal Other_Loan4_Amount { get; set; }
        public Nullable<int> Other_Loan5_Type { get; set; }
        public decimal Other_Loan5_Amount { get; set; }
        public Nullable<int> Other_Loan6_Type { get; set; }
        public decimal Other_Loan6_Amount { get; set; }
        public decimal Conventional_Loan_Total_Financing_Sum { get; set; }
        public Nullable<int> Islamic_Loan_Type { get; set; }
        public Nullable<int> Islamic_Financing_Type { get; set; }
        public decimal Islamic_Financing_Amount { get; set; }
        public Nullable<int> Other_Financing1_Type { get; set; }
        public decimal Other_Financing1_Amount { get; set; }
        public Nullable<int> Other_Financing2_Type { get; set; }
        public decimal Other_Financing2_Amount { get; set; }
        public Nullable<int> Other_Financing3_Type { get; set; }
        public decimal Other_Financing3_Amount { get; set; }
        public Nullable<int> Other_Financing4_Type { get; set; }
        public decimal Other_Financing4_Amount { get; set; }
        public Nullable<int> Other_Financing5_Type { get; set; }
        public decimal Other_Financing5_Amount { get; set; }
        public decimal Islamic_Loan_Total_Financing_Sum { get; set; }
        public decimal Bank_Selling_Price { get; set; }
        public decimal Bank_Purchase_Price { get; set; }
        public string Other_Islamic_Loan1_Bank_Name { get; set; }
        public Nullable<int> Other_Islamic_Loan1_Product_Type { get; set; }
        public string Other_Islamic_Loan1_Specification { get; set; }
        public decimal Other_Islamic_Loan1_Amount { get; set; }
        public decimal Other_Islamic_Loan1_Unit_Percentage { get; set; }
        public string Other_Islamic_Loan1_Ref { get; set; }
        public string Other_Islamic_Loan2_Bank_Name { get; set; }
        public Nullable<int> Other_Islamic_Loan2_Product_Type { get; set; }
        public string Other_Islamic_Loan2_Specification { get; set; }
        public decimal Other_Islamic_Loan2_Amount { get; set; }
        public decimal Other_Islamic_Loan2_Unit_Percentage { get; set; }
        public string Other_Islamic_Loan2_Ref { get; set; }
        public string Other_Islamic_Loan3_Bank_Name { get; set; }
        public Nullable<int> Other_Islamic_Loan3_Product_Type { get; set; }
        public string Other_Islamic_Loan3_Specification { get; set; }
        public decimal Other_Islamic_Loan3_Amount { get; set; }
        public decimal Other_Islamic_Loan3_Unit_Percentage { get; set; }
        public string Other_Islamic_Loan3_Ref { get; set; }
        public Nullable<int> Bank_Solicitor_ID { get; set; }
        public string Bank_Solicitor_Firm_Phone_No { get; set; }
        public string Bank_Solicitor_Email { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public int Officer1_Id { get; set; }
        public int Officer2_Id { get; set; }
        public string Other_Islamic_Loan4_Bank_Name { get; set; }
        public Nullable<int> Other_Islamic_Loan4_Product_Type { get; set; }
        public string Other_Islamic_Loan4_Specification { get; set; }
        public decimal Other_Islamic_Loan4_Amount { get; set; }
        public decimal Other_Islamic_Loan4_Unit_Percentage { get; set; }
        public string Other_Islamic_Loan4_Ref { get; set; }
        public string Other_Islamic_Loan5_Bank_Name { get; set; }
        public Nullable<int> Other_Islamic_Loan5_Product_Type { get; set; }
        public string Other_Islamic_Loan5_Specification { get; set; }
        public decimal Other_Islamic_Loan5_Amount { get; set; }
        public decimal Other_Islamic_Loan5_Unit_Percentage { get; set; }
        public string Other_Islamic_Loan5_Ref { get; set; }
        public string Other_Islamic_Loan6_Bank_Name { get; set; }
        public Nullable<int> Other_Islamic_Loan6_Product_Type { get; set; }
        public string Other_Islamic_Loan6_Specification { get; set; }
        public decimal Other_Islamic_Loan6_Amount { get; set; }
        public decimal Other_Islamic_Loan6_Unit_Percentage { get; set; }
        public string Other_Islamic_Loan6_Ref { get; set; }
        public string Other_Islamic_Loan7_Bank_Name { get; set; }
        public Nullable<int> Other_Islamic_Loan7_Product_Type { get; set; }
        public string Other_Islamic_Loan7_Specification { get; set; }
        public decimal Other_Islamic_Loan7_Amount { get; set; }
        public decimal Other_Islamic_Loan7_Unit_Percentage { get; set; }
        public string Other_Islamic_Loan7_Ref { get; set; }
        public string Bank_Solicitor_Firm_Address1 { get; set; }
        public string Bank_Solicitor_Firm_Address2 { get; set; }
        public string Bank_Solicitor_Firm_Postcode { get; set; }
        public string Bank_Solicitor_Firm_City { get; set; }
        public string Bank_Solicitor_Firm_State { get; set; }
        public string Bank_Solicitor_Ref { get; set; }
    }
}
