//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSLcLy.Data.DbModels
{
    using System;
    using System.Collections.Generic;

    [System.ComponentModel.DataAnnotations.Schema.Table("workflow")]
    public partial class workflow
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int ID { get; set; }
        public string WorkflowDescrption { get; set; }
        public string WorkflowDescrption_BM { get; set; }
        public string WorkflowDescrption_CN { get; set; }
        public Nullable<int> WorkflowTotalDuration { get; set; }
        public Nullable<int> CriticalDuration { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
