//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSLcLy.Data.DbModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DefaultConnection : DbContext
    {
        public DefaultConnection()
            : base("name=DefaultConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aspnetrole> aspnetroles { get; set; }
        public virtual DbSet<aspnetuserclaim> aspnetuserclaims { get; set; }
        public virtual DbSet<aspnetuserlogin> aspnetuserlogins { get; set; }
        public virtual DbSet<aspnetuser> aspnetusers { get; set; }
        public virtual DbSet<bankmaster> bankmasters { get; set; }
        public virtual DbSet<documentworkflow> documentworkflows { get; set; }
        public virtual DbSet<userdetail> userdetails { get; set; }
        public virtual DbSet<usermaster> usermasters { get; set; }
        public virtual DbSet<workflow> workflows { get; set; }
        public virtual DbSet<workflowdetail> workflowdetails { get; set; }
        public virtual DbSet<workflowmaster> workflowmasters { get; set; }
    }
}
