//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSLcLy.Data.DbModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [System.ComponentModel.DataAnnotations.Schema.Table("aspnetuserlogins")]
    public partial class aspnetuserlogin
    {
        [System.ComponentModel.DataAnnotations.Key]
        [Column(Order = 1)]
        public string LoginProvider { get; set; }
        [System.ComponentModel.DataAnnotations.Key]
        [Column(Order = 2)]
        public string ProviderKey { get; set; }
        [System.ComponentModel.DataAnnotations.Key]
        [Column(Order = 3)]
        public string UserId { get; set; }
    
        public virtual aspnetuser aspnetuser { get; set; }
    }
}
